# Unique project key for SonarQube
sonar.projectKey=MiguelCiav_chil
sonar.projectName=chil

# Organization key (required if using SonarCloud, e.g., sonar.organization=miguelciav)
sonar.organization=miguelciav

# Paths to source files
sonar.sources=src,functions

# Exclusions
sonar.exclusions=node_modules/**,dist/**,functions/node_modules/**,.firebase/**,**/__tests__/**,**/*.test.tsx,**/*.test.ts

# Paths to test files
sonar.tests=src
sonar.test.inclusions=**/__tests__/**,**/*.test.tsx,**/*.test.ts

# Source encoding
sonar.sourceEncoding=UTF-8

# Coverage reports paths
sonar.javascript.lcov.reportPaths=coverage/lcov.info
